### ISSUE TITLE
Can not use in a lazy-loaded feature module

### ISSUE THREAD

**Issue by JonYildiz** [arkon/ng2-sidebar#12]
>  Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

We are trying to use the module in a lazy loaded feature module.  The error comes because [you can not import Browser Module in a feature module](https://angular.io/docs/ts/latest/cookbook/ngmodule-faq.html#q-browser-vs-common-module).  By using the CommonModule it will be more universally usable.

I have updated it locally by replacing the BrowserModule import with the CommonModule import and it is now working.

**Comment by arkon** [comment]
Hey, thanks for reporting this! I've published v1.3.1 with this fix.
