### ISSUE TITLE
Experimental support for decorators

### ISSUE THREAD

**Issue by MichaelNeas** [arkon/ng2-sidebar#13]
I am able to install and start a local version of your repo but when i open a component in my editor, say the Sidebar class i get an error:

> experimental support for decorators is a feature that is subject to change in a future release

Have you run into this before?

I am running tsc -v 1.8.10, if that helps?

**Comment by arkon** [comment]
You should be using TypeScript 2.x since I'm using the `include` property in my [tsconfig.json](https://github.com/arkon/ng2-sidebar/blob/master/tsconfig.json).

**Comment by MichaelNeas** [comment]
Upgraded to 2.0.0, then to Version 2.1.0-dev.20161002 and still receiving the error

**Comment by arkon** [comment]
What editor are you using? If it's VS Code, you might need to make sure you configure it to use 2.x.

**Comment by MichaelNeas** [comment]
I'm using Sublime Text, weird though, magically the errors just disappeared and I don't know why lol, thanks for the speedy replies

**Comment by arkon** [comment]
Well that works then. 👍
