### ISSUE TITLE
Compatibility for browsers that not support Web Animations API

### ISSUE THREAD

**Issue by Sifawm** [arkon/ng2-sidebar#16]
The module animate uses Web Animations API. This functionality is only for **Firefox**, **Chrome**, **Opera** and not completely. From the angular official docs recommends use [web-animations.js](https://github.com/web-animations/web-animations-js)

I think that is a good idea to add this advice to README.

Note: Thank you for the hard work.

**Comment by arkon** [comment]
Good point! I've added a note in the README in commit 1525b10a45dc352fa424a3f2d1733fbe5b128ff0.
