### ISSUE TITLE
Sidebar not found

### ISSUE THREAD

**Issue by benitazz** [arkon/ng2-sidebar#17]
Greatings,

I have installed ng2-sibebar successfully

package.json:
                     "dependencies": {
    "@angular/common": "~2.1.0",
    "@angular/compiler": "~2.1.0",
    "@angular/core": "~2.1.0",
    "@angular/forms": "~2.1.0",
    "@angular/http": "~2.1.0",
    "@angular/platform-browser": "~2.1.0",
    "@angular/platform-browser-dynamic": "~2.1.0",
    "@angular/router": "~3.1.0",
    "@angular/upgrade": "~2.1.0",
    "angular-in-memory-web-api": "~0.1.5",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "ng2-sidebar": "^1.6.1",

app.module:
           import { SidebarModule } from 'ng2-sidebar';
        @NgModule({
            imports: [ SidebarModule],

Error Message: 
"(SystemJS) XHR error (404 Not Found) loading http://localhost:3000/ng2-sidebar
    Error: XHR error (404 Not Found) loading http://localhost:3000/ng2-sidebar
       at wrapFn (http://localhost:3000/node_modules/zone.js/dist/zone.js:698:17)
       at ZoneDelegate.prototype.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:263:17)
       at Zone.prototype.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:154:21)
       at invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:335:21)
    Error loading http://localhost:3000/ng2-sidebar as "ng2-sidebar" from http://localhost:3000/app/app.module.js"

**Comment by arkon** [comment]
@benitazz Are you using SystemJS to load modules?

**Comment by benitazz** [comment]
Yes I'm using SystemJS

 map: {
      // our app is within the app folder
      app: 'app',
      // angular bundles
      '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
      '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
      '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
      '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
      '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
      '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
      '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
      '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
      // other libraries
      'rxjs':                      'npm:rxjs',
      'angular-in-memory-web-api': 'npm:angular-in-memory-web-api',    
    },

**Comment by arkon** [comment]
Whoops, I didn't include the SystemJS instructions.

Could you try adding the following to that map:

```js
'ng2-sidebar': 'npm:ng2-sidebar/lib/index.js'
```

**Comment by benitazz** [comment]
After I have added:  'ng2-sidebar': 'npm:ng2-sidebar/lib/index.js'

HTML1300: Navigation occurred.
localhost:3002
HTML1527: DOCTYPE expected. Consider adding a valid HTML5 doctype: "<!DOCTYPE html>".
localhost:3002 (1,1)
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
localhost:3002
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR): GET - http://localhost:3002/node_modules/ng2-sidebar/lib/sidebar.component
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR): GET - http://localhost:3002/node_modules/ng2-sidebar/lib/close.directive
Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3002/node_modules/ng2-sidebar/lib/sidebar.component
	Error: XHR error (404 Not Found) loading http://localhost:3002/node_modules/ng2-sidebar/lib/sidebar.component
	   at wrapFn (http://localhost:3002/node_modules/zone.js/dist/zone.js:698:17)
	   at ZoneDelegate.prototype.invokeTask (http://localhost:3002/node_modules/zone.js/dist/zone.js:263:17)
	   at Zone.prototype.runTask (http://localhost:3002/node_modules/zone.js/dist/zone.js:154:21)
	   at invoke (http://localhost:3002/node_modules/zone.js/dist/zone.js:335:21)
	Error loading http://localhost:3002/node_modules/ng2-sidebar/lib/sidebar.component as "./sidebar.component" from http://localhost:3002/node_modules/ng2-sidebar/lib/index.js
localhost:3002 (16,49)
   {
      [functions]: ,
      __proto__: { },
      description: "(SystemJS) XHR error (404 Not Found) loading http://localhost:3002/node_modules/ng2-sidebar/lib/sidebar.component
	Error: XHR error (404 Not Found) loading http://localhost:3002/node_modules/ng2-sidebar/lib/sidebar.component
	   at wrapFn (http://localhost:3002/node_modules/zone.js/dist/zone.js:698:17)
	   at ZoneDelegate.prototype.invokeTask (http://localhost:3002/node_modules/zone.js/dist/zone.js:263:17)
	   at Zone.prototype.runTask (http://localhost:3002/node_modules/zone.js/dist/zone.js:154:21)
	   at invoke (http://localhost:3002/node_modules/zone.js/dist/zone.js:335:21)
	Error loading http://localhost:3002/node_modules/ng2-sidebar/lib/sidebar.component as "./sidebar.component" from http://localhost:3002/node_modules/ng2-sidebar/lib/index.js",
      message: "(SystemJS) XHR error (404 Not Found) loading http://localhost:3002/node_modules/ng2-sidebar/lib/sidebar.component
	Error: XHR error (404 Not Found) loading http://localhost:3002/node_modules/ng2-sidebar/lib/sidebar.component
	   at wrapFn (http://localhost:3002/node_modules/zone.js/dist/zone.js:698:17)
	   at ZoneDelegate.prototype.invokeTask (http://localhost:3002/node_modules/zone.js/dist/zone.js:263:17)
	   at Zone.prototype.runTask (http://localhost:3002/node_modules/zone.js/dist/zone.js:154:21)
	   at invoke (http://localhost:3002/node_modules/zone.js/dist/zone.js:335:21)
	Error loading http://localhost:3002/node_modules/ng2-sidebar/lib/sidebar.component as "./sidebar.component" from http://localhost:3002/node_modules/ng2-sidebar/lib/index.js",
      name: "Error",
      originalErr: { },
      stack: "(SystemJS) XHR error (404 Not Found) loading http://localhost:3002/node_modules/ng2-sidebar/lib/sidebar.component
	Error: XHR error (404 Not Found) loading http://localhost:3002/node_modules/ng2-sidebar/lib/sidebar.component
	   at wrapFn (http://localhost:3002/node_modules/zone.js/dist/zone.js:698:17)
	   at ZoneDelegate.prototype.invokeTask (http://localhost:3002/node_modules/zone.js/dist/zone.js:263:17)
	   at Zone.prototype.runTask (http://localhost:3002/node_modules/zone.js/dist/zone.js:154:21)
	   at invoke (http://localhost:3002/node_modules/zone.js/dist/zone.js:335:21)
	Error loading http://localhost:3002/node_modules/ng2-sidebar/lib/sidebar.component as "./sidebar.component" from http://localhost:3002/node_modules/ng2-sidebar/lib/index.js"
   }

**Comment by benitazz** [comment]
![image](https://cloud.githubusercontent.com/assets/3354516/19521427/ecc5a0b6-9613-11e6-9e5f-fa91637b5be4.png)

**Comment by arkon** [comment]
Seems like it's missing the JS files for some reason. Could you try re-installing? I just installed a fresh copy from NPM and the files are there.

**Comment by benitazz** [comment]
I have uninstalled and reinstalled the ng2-sidebar, here are the files in the lib folders

![image](https://cloud.githubusercontent.com/assets/3354516/19550405/850577a8-96a9-11e6-9c62-ca4be8a81696.png)

**Comment by benitazz** [comment]
HTML1300: Navigation occurred.
localhost:3002
HTML1527: DOCTYPE expected. Consider adding a valid HTML5 doctype: "<!DOCTYPE html>".
localhost:3002 (1,1)
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
localhost:3002
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR): GET - http://localhost:3002/node_modules/ng2-sidebar/lib/sidebar.component
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR): GET - http://localhost:3002/node_modules/ng2-sidebar/lib/close.directive
Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3002/node_modules/ng2-sidebar/lib/sidebar.component
	Error: XHR error (404 Not Found) loading http://localhost:3002/node_modules/ng2-sidebar/lib/sidebar.component
	   at wrapFn (http://localhost:3002/node_modules/zone.js/dist/zone.js:698:17)
	   at ZoneDelegate.prototype.invokeTask (http://localhost:3002/node_modules/zone.js/dist/zone.js:263:17)
	   at Zone.prototype.runTask (http://localhost:3002/node_modules/zone.js/dist/zone.js:154:21)
	   at invoke (http://localhost:3002/node_modules/zone.js/dist/zone.js:335:21)
	Error loading http://localhost:3002/node_modules/ng2-sidebar/lib/sidebar.component as "./sidebar.component" from http://localhost:3002/node_modules/ng2-sidebar/lib/index.js
localhost:3002 (16,49)
   {
      [functions]: ,
      __proto__: { },
      description: "(SystemJS) XHR error (404 Not Found) loading http://localhost:3002/node_modules/ng2-sidebar/lib/sidebar.component
	Error: XHR error (404 Not Found) loading http://localhost:3002/node_modules/ng2-sidebar/lib/sidebar.component
	   at wrapFn (http://localhost:3002/node_modules/zone.js/dist/zone.js:698:17)
	   at ZoneDelegate.prototype.invokeTask (http://localhost:3002/node_modules/zone.js/dist/zone.js:263:17)
	   at Zone.prototype.runTask (http://localhost:3002/node_modules/zone.js/dist/zone.js:154:21)
	   at invoke (http://localhost:3002/node_modules/zone.js/dist/zone.js:335:21)
	Error loading http://localhost:3002/node_modules/ng2-sidebar/lib/sidebar.component as "./sidebar.component" from http://localhost:3002/node_modules/ng2-sidebar/lib/index.js",
      message: "(SystemJS) XHR error (404 Not Found) loading http://localhost:3002/node_modules/ng2-sidebar/lib/sidebar.component
	Error: XHR error (404 Not Found) loading http://localhost:3002/node_modules/ng2-sidebar/lib/sidebar.component
	   at wrapFn (http://localhost:3002/node_modules/zone.js/dist/zone.js:698:17)
	   at ZoneDelegate.prototype.invokeTask (http://localhost:3002/node_modules/zone.js/dist/zone.js:263:17)
	   at Zone.prototype.runTask (http://localhost:3002/node_modules/zone.js/dist/zone.js:154:21)
	   at invoke (http://localhost:3002/node_modules/zone.js/dist/zone.js:335:21)
	Error loading http://localhost:3002/node_modules/ng2-sidebar/lib/sidebar.component as "./sidebar.component" from http://localhost:3002/node_modules/ng2-sidebar/lib/index.js",
      name: "Error",
      originalErr: { },
      stack: "(SystemJS) XHR error (404 Not Found) loading http://localhost:3002/node_modules/ng2-sidebar/lib/sidebar.component
	Error: XHR error (404 Not Found) loading http://localhost:3002/node_modules/ng2-sidebar/lib/sidebar.component
	   at wrapFn (http://localhost:3002/node_modules/zone.js/dist/zone.js:698:17)
	   at ZoneDelegate.prototype.invokeTask (http://localhost:3002/node_modules/zone.js/dist/zone.js:263:17)
	   at Zone.prototype.runTask (http://localhost:3002/node_modules/zone.js/dist/zone.js:154:21)
	   at invoke (http://localhost:3002/node_modules/zone.js/dist/zone.js:335:21)
	Error loading http://localhost:3002/node_modules/ng2-sidebar/lib/sidebar.component as "./sidebar.component" from http://localhost:3002/node_modules/ng2-sidebar/lib/index.js"
   }

**Comment by arkon** [comment]
Can you [try this](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#defaultjsextensions)?

**Comment by arkon** [comment]
@benitazz Any luck?

**Comment by benitazz** [comment]
Sorry buddy, I was away.
I will try that and let you

**Comment by josephkkin** [comment]
I too had a similar issue with the sidebar component not being found during runtime. It turned out that I had to include the SidebarModule in all the modules I was using the component. If it helps you to resolve this issue, here is what I had to do, to get it working.

My application structure is like

```
App Module
|-- Feature Module 1
     |-- Feature Component 1 (Uses ng2-sidebar)
```

**1. SystemJS configuration**
```
    // map tells the System loader where to look for things
    var map = {
        ...
        'ng2-sidebar': 'node_modules/ng2-sidebar',
        ...
    };
    // packages tells the System loader how to load when no filename and/or no extension
    var packages = {
       ...
        'ng2-sidebar': {
            main: 'lib/index',
            defaultExtension: 'js'
        }
    };
```

**2. App Module configuration**

```
import { SidebarModule } from 'ng2-sidebar'
...
@NgModule({
    imports: [
        ...
        SidebarModule
    ],
    ...
})
```

**3. Feature Module 1 configuration**
```
import { SidebarModule } from 'ng2-sidebar'
...
@NgModule({
    imports: [... , SidebarModule],
    ...
})
```

**4. Include it in Feature Component 1** 

```
<ng2-sidebar 
		[(open)]="isSidebarOpen"
		[defaultStyles]="true"
		[position]="_POSITIONS[_positionNum]"
		[closeOnClickOutside]="_closeOnClickOutside"
		[showOverlay]="_showOverlay"
		[animate]="_animate"
		[trapFocus]="_trapFocus"
		[sidebarClass]="'demo-sidebar'">
		<p>
			Side bar contents
		</p>
</ng2-sidebar>
<button (click)="toggleSidebar()">Toggle sidebar</button>
```

**Comment by IvanAR** [comment]
@josephkkin worked for me

**Comment by arkon** [comment]
@josephkkin @IvanAR Thanks for chipping in. I haven't been actively using Angular 2 as much recently, so I'm not super familiar with how imports are supposed to propagate to feature modules (if they do at all).

I'll update the README with this info and close this issue. 👍

**Comment by benitazz** [comment]
Thanks all
