### ISSUE TITLE
sidebarClass not working

### ISSUE THREAD

**Issue by vgosain91** [arkon/ng2-sidebar#20]

**Comment by vgosain91** [comment]
sidebarClass property not working

**Comment by arkon** [comment]
Are you getting some error, or is the class name just not showing up on the element?

**Comment by vgosain91** [comment]
class name not showing on element. can you show me some sample code to add class name using sidebarClass?

**Comment by arkon** [comment]
The code for the [demo](https://echeung.me/ng2-sidebar/) can be found [here](https://github.com/arkon/ng2-sidebar/blob/master/demo/src/demo/demo.component.ts#L15). If you actually inspect the elements on the demo site, you'll see that `demo-sidebar` is in the injected `aside` element's class names.

**Comment by vgosain91** [comment]
ok thank you for your help

**Comment by vgosain91** [comment]
my customclass name is added to the element but when i add my class in one of the styleUrls file , its value is not reflected in the side bar ,maybe because angular 2 changes name of the class so that it is applicable for that html view only not others, does that mean that i have to add the class name in global css file?

**Comment by arkon** [comment]
I think there's workarounds for that like using `/deep/` or `::shadow`, but I'm not sure what the actual recommended way of handling it is, since the discussions in [@angular/angular#5064](https://github.com/angular/angular/issues/5064) didn't seem to get very far.

**Comment by arkon** [comment]
I'll close this because I _think_ using `/deep/` is how you're supposed to "fix" this.
