### ISSUE TITLE
Not able to integrate ng2-sidebar in application

### ISSUE THREAD

**Issue by harishrohokale** [arkon/ng2-sidebar#23]
Hi 

I am getting below error after following the steps : 

**localhost/:52 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/node_modules/ng2-sidebar.js
	Error: XHR error (404 Not Found) loading http://localhost:3000/node_modules/ng2-sidebar.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js?1478617667938:647:29)
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js?1478617667938:236:37)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js?1478617667938:136:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js?1478617667938:304:33)
	Error loading http://localhost:3000/node_modules/ng2-sidebar.js as "ng2-sidebar" from http://localhost:3000/app/shared/shared.module.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js?1478617667938:647:29)
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js?1478617667938:236:37)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js?1478617667938:136:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js?1478617667938:304:33)
	Error loading http://localhost:3000/node_modules/ng2-sidebar.js as "ng2-sidebar" from http://localhost:3000/app/shared/shared.module.js "Error while loading app"**

Could you please help me on this?
Am i missing anything?

**Comment by arkon** [comment]
What does your SystemJS config look like?

**Comment by harishrohokale** [comment]
/**
   * The system builder configuration of the application.
   * @type {any}
   */
  SYSTEM_BUILDER_CONFIG: any = {
    defaultJSExtensions: true,
    base: this.PROJECT_ROOT,
    packageConfigPaths: [
      join('node_modules', '*', 'package.json'),
      join('node_modules', '@angular', '*', 'package.json')
    ],
    paths: {
      // Note that for multiple apps this configuration need to be updated
      // You will have to include entries for each individual application in
      // `src/client`.
      [join(this.TMP_DIR, this.BOOTSTRAP_DIR, '*')]: `${this.TMP_DIR}/${this.BOOTSTRAP_DIR}/*`,
      'node_modules/*': 'node_modules/*',
      '*': 'node_modules/*'
    },
    map:{
      // ...
      'ng2-sidebar': 'node_modules/ng2-sidebar',
      // ...
    },
    packages: {
      '@angular/common': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/compiler': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/core/testing': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/core': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/forms': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/http': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/platform-browser': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/platform-browser-dynamic': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/router': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      'rxjs': {
        main: 'Rx.js',
        defaultExtension: 'js'
      }
      ,
      'ng2-sidebar': {
        main: 'lib/index',
        defaultExtension: 'js'
      }
    }
  }
    ;

I am following the angular-seed project structure.

**Comment by arkon** [comment]
Maybe try `'ng2-sidebar': 'node_modules/ng2-sidebar/lib/index.js'` in the map? Unfortunately, I don't use SystemJS so I can't provide much help.
