### ISSUE TITLE
Add "focusFirstItem" input to enable/disable first focusable item autofocus.

### ISSUE THREAD

**Issue by pablodoble** [arkon/ng2-sidebar#24]
Hi @arkon.

I'm developing an Angular2 app using your sidebar component and it's really good. The problem is that I have an input tag into a sidebar and it's autofocused when the sidebar opens. In desktop browsers it's not a  big deal, but in mobile browsers it causes the keyboard to raise up automatically and it disturbs the user experience a little bit on my opinion. So what do you think about adding a "focusFirstItem" input flag on the sidebar component (that could be true by default) to avoid this in case the developer wants to? I'm able to make a PR if you agree.

Regards and thanks again!

**Comment by arkon** [comment]
Good idea! I'd be thrilled if you can make a PR. Perhaps consider calling it "autofocus"?

**Comment by arkon** [comment]
Done via #26
