### ISSUE TITLE
Disable mouse click/hover events for page elements beneath the overlay 

### ISSUE THREAD

**Issue by benje** [arkon/ng2-sidebar#25]
When using the showOverlay = true option, links and other DOM elements respond to my mouse cursor (hover styles and click events) when moving my mouse around the sidebar overlay.

This can cause an unexpected side effect of the user accidentally clicking a link when just trying to close the sidebar.

It would be much better to disable mouse events underneath the overlay, such as the behaviour of Bootstrap modals (http://getbootstrap.com/javascript/#modals).

I have had a quick look through the source code, and I can see 'pointer-events' is set to 'none', and I am not 100% sure how to approach fixing this.

Happy to attempt a fix and submit a PR if someone could point me in the right direction?

Thanks and good job on the package! 👍

**Comment by arkon** [comment]
Whoops, that's actually a mistake. I've published v1.6.3, which should fix it.

**Comment by benje** [comment]
Wow that was insanely fast! Thank you @arkon worked like a charm
